### ISSUE TITLE
Error executing migrate command

### ISSUE THREAD

**Issue by DeepPurohit** [upperwal/OpenComplainNetwork#1]
Hello, first of all it is a great project. Though while running the migrate command, an error is coming : 

> Attempting to run transaction which calls a contract function, but recipient address 0x9fbda871d559710256a2502a2517b794b482db40 is not a contract address
>     at Object.InvalidResponse (/usr/lib/node_modules/truffle/build/webpack:/~/web3/lib/web3/errors.js:38:1)
>     
Please revert as how to solve this error.

**Comment by upperwal** [comment]
try deleting "src/truffle-contract/build" folder. It will auto generate when you run compile.

**Comment by DeepPurohit** [comment]
After following that step, it shows this error
```./src/Components/Pages/Accounts/accounts.js
Module not found: Can't resolve 'wb3' in '/home/deep/Desktop/OpenComplainNetwork-master/src/Components/Pages/Accounts'
```

**Comment by upperwal** [comment]
Do you mean ```'web3'```? Try doing ```npm install``` in the project root folder. It will install all the dependencies.

**Comment by DeepPurohit** [comment]
still it shows error
```
./node_modules/web3/packages/web3-utils/src/utils.js
Module not found: Can't resolve 'eth-lib/src/hash' in '/home/deep/Desktop/OpenComplainNetwork-master/node_modules/web3/packages/web3-utils/src'
```

**Comment by upperwal** [comment]
This problem is because of broken dependencies of ```"web3": "^1.0.0-beta.24"```. Solution would be to downgrade the web3 version but then web3 API calls needs to be updated through out the project.

**Comment by upperwal** [comment]
Its working:
Try using npm v5.8.0 and nodejsv9.9.0

**Comment by DeepPurohit** [comment]
ok
